apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-disk-1
spec:
  capacity:
    storage: 1.8Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: minio-storage
  hostPath:
    path: /DISK1