apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 3  # 원하는 복제본 수로 변경
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-app
        image: docker.bestpath.co.kr/api:latest  # Docker 이미지의 경로와 태그를 입력
        ports:
        - containerPort: 80  # FastAPI 애플리케이션이 서비스하는 포트를 입력