apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: LoadBalancer
  selector:
    app: fastapi-app
  ports:
  - protocol: TCP
    port: 80  # 서비스 포트
    targetPort: 80  # FastAPI 애플리케이션이 서비스하는 포트와 동일하게 설정